# Numpy

Материалы:
* Макрушин С.В. "Лекция 1: Библиотека Numpy"
* https://numpy.org/doc/stable/user/index.html
* https://numpy.org/doc/stable/reference/index.html

## Задачи для совместного разбора

1. Сгенерировать двухмерный массив `arr` размерности (4, 7), состоящий из случайных действительных чисел, равномерно распределенных в диапазоне от 0 до 20. Нормализовать значения массива с помощью преобразования вида  $𝑎𝑥+𝑏$  так, что после нормализации максимальный элемент масcива будет равен 1.0, минимальный 0.0

In [4]:
import numpy as np
arr=np.linspace(0, 20, num=4*7).reshape(4,7)
arr/20

array([[0.        , 0.03703704, 0.07407407, 0.11111111, 0.14814815,
        0.18518519, 0.22222222],
       [0.25925926, 0.2962963 , 0.33333333, 0.37037037, 0.40740741,
        0.44444444, 0.48148148],
       [0.51851852, 0.55555556, 0.59259259, 0.62962963, 0.66666667,
        0.7037037 , 0.74074074],
       [0.77777778, 0.81481481, 0.85185185, 0.88888889, 0.92592593,
        0.96296296, 1.        ]])

2. Создать матрицу 8 на 10 из случайных целых (используя модуль `numpy.random`) чисел из диапозона от 0 до 10 и найти в ней строку (ее индекс и вывести саму строку), в которой сумма значений минимальна.

In [5]:
a4 =np.random.randint(0,10,(8,10))
stroki = a4.sum(axis=1)

stroki.argmin(), a4[stroki.argmin()]


(2, array([1, 3, 7, 1, 8, 4, 5, 0, 6, 0]))

In [6]:
a4

array([[9, 1, 4, 6, 3, 6, 0, 2, 2, 5],
       [6, 4, 8, 1, 4, 1, 7, 8, 0, 8],
       [1, 3, 7, 1, 8, 4, 5, 0, 6, 0],
       [8, 2, 2, 4, 7, 3, 4, 9, 6, 9],
       [3, 9, 3, 5, 3, 5, 7, 9, 0, 7],
       [7, 0, 6, 8, 4, 5, 6, 5, 0, 0],
       [4, 6, 2, 1, 1, 6, 3, 9, 6, 9],
       [6, 6, 5, 2, 8, 5, 5, 4, 5, 6]])

3. Найти евклидово расстояние между двумя одномерными векторами одинаковой размерности.

In [7]:
# Initializing the points
point_1 = np.array((0, 0, 0))
point_2 = np.array((3, 3, 3))
# Get the square of the difference of the 2 vectors
square = np.square(point_1 - point_2)
# Get the sum of the square
sum_square = np.sum(square)
# The last step is to get the square root and print the Euclidean distance
distance = np.sqrt(sum_square)
distance

5.196152422706632

In [8]:
np.linalg.norm(point_1 - point_2)

5.196152422706632

4. Решить матричное уравнение `A*X*B=-C` - найти матрицу `X`. Где `A = [[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]`, `B=[[3, -1], [2, 1]]`, `C=[[7, 21], [11, 8], [8, 4]]`.

In [9]:
A = np.matrix([[-1, 2, 4], [-3, 1, 2], [-3, 0, 1]]) 
B = np.matrix([[3, -1], [2, 1]]) 
C = np.matrix([[7, 21], [11, 8], [8, 4]])

In [10]:
np.matmul(np.matmul(np.linalg.inv(A), (-C)), np.linalg.inv(B))

matrix([[ 1.00000000e+00,  1.11022302e-15],
        [-2.00000000e+00,  1.00000000e+00],
        [ 3.00000000e+00, -4.00000000e+00]])

## Лабораторная работа №1.1

Замечание: при решении данных задач не подразумевается использования циклов или генераторов Python, если в задании не сказано обратного. Решение должно опираться на использования функционала библиотеки `numpy`.

1. Файл `minutes_n_ingredients.csv` содержит информацию об идентификаторе рецепта, времени его выполнения в минутах и количестве необходимых ингредиентов. Считайте данные из этого файла в виде массива `numpy` типа `int32`, используя `np.loadtxt`. Выведите на экран первые 5 строк массива.

In [11]:
dataset = np.loadtxt(r"minutes_n_ingredients.csv", 
                     delimiter=',', skiprows=1, dtype=np.int32)
dataset[:5]

array([[127244,     60,     16],
       [ 23891,     25,      7],
       [ 94746,     10,      6],
       [ 67660,      5,      6],
       [157911,     60,     14]])

2. Вычислите среднее значение, минимум, максимум и медиану по каждому из столбцов, кроме первого.

In [12]:
print(dataset[:, 1:].mean(axis=0),
      dataset[:, 1:].min(axis=0),
      dataset[:, 1:].max(axis=0),
      np.median(dataset[:, 1:], axis=0), sep='\n')

[2.16010017e+04 9.05528000e+00]
[0 1]
[2147483647         39]
[40.  9.]


3. Ограничьте сверху значения продолжительности выполнения рецепта значением квантиля $q_{0.75}$. 

In [13]:
print(np.quantile(dataset[:,1], 0.75))

65.0


4. Посчитайте, для скольких рецептов указана продолжительность, равная нулю. Замените для таких строк значение в данном столбце на 1.

In [14]:
print("Число 0 до замены: ", np.sum(dataset[:,1] == 0))
x = np.maximum(dataset[:,1], 1)  
print(x)
print("Число 0 после замены: ", np.sum(x == 0)) #Для проверки правильности

Число 0 до замены:  479
[ 60  25  10 ...  65   5 140]
Число 0 после замены:  0


5. Посчитайте, сколько уникальных рецептов находится в датасете.

In [15]:
print(len(np.unique(dataset[:, 0])))

100000


6. Сколько и каких различных значений кол-ва ингредиентов присутвует в рецептах из датасета?

In [16]:
print("Всего: ", len(dataset[:, 2]),"\nУникальных: ", len(np.unique(dataset[:,2])))

Всего:  100000 
Уникальных:  37


## Лабораторная работа №1.2

7. Создайте версию массива, содержащую информацию только о рецептах, состоящих не более чем из 5 ингредиентов.

In [29]:
dataset[dataset[:, 2] <= 5]

array([[446597,     15,      5],
       [204134,      5,      3],
       [ 25623,      6,      4],
       ...,
       [ 52088,     60,      5],
       [128811,     15,      4],
       [370915,      5,      4]])

8. Для каждого рецепта посчитайте, сколько в среднем ингредиентов приходится на одну минуту рецепта. Найдите максимальное значение этой величины для всего датасета

In [35]:
dataset[:, 2] / dataset[:, 1]

<ipython-input-35-2b70d81fc300>:1: RuntimeWarning: divide by zero encountered in true_divide
  dataset[:, 2] / dataset[:, 1]


array([0.26666667, 0.28      , 0.6       , ..., 0.23076923, 0.8       ,
       0.1       ])

In [36]:
(dataset[:, 2] / dataset[:, 1]).max()

<ipython-input-36-f9cbba1f35f6>:1: RuntimeWarning: divide by zero encountered in true_divide
  (dataset[:, 2] / dataset[:, 1]).max()


inf

9. Вычислите среднее количество ингредиентов для топ-100 рецептов с наибольшей продолжительностью

In [51]:
arr = dataset[:, 1].argsort()[-100:]
#print(arr)
dataset[arr, 2].mean()

[27451 95235  2141 67378 53610 68135   260 32405 33606 40201 28374 64150
 67503 94179 29609 58141 57389 66458 52519 80618 62987 15594 20170 58688
 55749 47824 86005 35863 31870 13374 14217 54083 28322 66448 44438 81672
 17798 12396  3533 37973 76588 29439 19388 62270 25245 92739 77027 17852
 39613 49730  7553 96659 14133 24169 73413 43472 46147 91383 71056 71064
 14301 12331 50674 10462 27922 67144 45140 76001 71876 54674 31122  2373
 18144 59983 56616 18907 27183 87101 78284 34013 98002 76018 37115 82026
 26073 51129 20782 41501 27143 68221 25344 66943 10299 69212 26714 22002
 77395 76939 39484 15653]


6.61

10. Выберите случайным образом и выведите информацию о 10 различных рецептах

In [52]:
dataset[np.random.randint(0, len(dataset), 10)]

array([[131158,     30,      8],
       [105292,     40,     10],
       [382269,     45,      8],
       [210622,     10,      6],
       [205778,     75,     10],
       [ 35168,     80,      7],
       [ 43802,     75,     11],
       [481109,     20,     12],
       [170758,     10,      6],
       [259213,     45,     15]])

11. Выведите процент рецептов, кол-во ингредиентов в которых меньше среднего.

In [53]:
len(dataset[:, 2] < dataset[:, 2].mean()) / len(dataset)

1.0

12. Назовем "простым" такой рецепт, длительность выполнения которого не больше 20 минут и кол-во ингредиентов в котором не больше 5. Создайте версию датасета с дополнительным столбцом, значениями которого являются 1, если рецепт простой, и 0 в противном случае.

In [54]:
dataset2 = np.zeros((len(dataset), 4), dtype = np.int32)
dataset2[:, :3] = dataset
dataset2[:, 3] = (dataset[:, 1] <= 20) & (dataset[:, 2] <= 5).astype(np.int32)

13. Выведите процент "простых" рецептов в датасете

In [55]:
ez  = (dataset2[:, -1] == 1).sum()
ez / len(dataset2), 1 - ez / len(dataset2)

(0.09552, 0.90448)

14. Разделим рецепты на группы по следующему правилу. Назовем рецепты короткими, если их продолжительность составляет менее 10 минут; стандартными, если их продолжительность составляет более 10, но менее 20 минут; и длинными, если их продолжительность составляет не менее 20 минут. Создайте трехмерный массив, где нулевая ось отвечает за номер группы (короткий, стандартный или длинный рецепт), первая ось - за сам рецепт и вторая ось - за характеристики рецепта. Выберите максимальное количество рецептов из каждой группы таким образом, чтобы было возможно сформировать трехмерный массив. Выведите форму полученного массива.

In [23]:
short = dataset[dataset[:, 2] < 10]
stardant = dataset[(dataset[:, 2] > 9) & (dataset[:, 2] < 20)]
long = dataset[dataset[:, 2] > 19]
mx = min(len(short), len(stardant), len(long))
x =np.stack([short[:mx],  stardant[:mx], long[:mx]])
x.shape

(3, 1074, 3)